#!/bin/bash

#initial update and install utility packages
apt-get update
apt-get install -y curl unzip apt-transport-https wget

#install java
apt-get install -y default-jre

#install dotnet
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list
apt-get update
apt-get install -y dotnet-sdk-2.1.3

#install profit trailer
wget https://github.com/taniman/profit-trailer/releases/download/v1.2.6.11/ProfitTrailer.zip
unzip ProfitTrailer.zip
rm ProfitTrailer.zip

#install profit feeder
mkdir ProfitFeeder
cd ProfitFeeder
wget https://github.com/mehtadone/PTFeeder/releases/download/pt-feeder-v1.3.4.236/pt-feeder-v1.3.4.236.zip
unzip pt-feeder-v1.3.4.236.zip
rm pt-feeder-v1.3.4.236.zip